services:
  - type: web
    name: elon-boys
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GMAIL_ADDRESS
        sync: false
      - key: MJ_APIKEY_PUBLIC
        sync: false
      - key: MJ_APIKEY_PRIVATE
        sync: false
