"""
Generates SQL INSERT statements for seeding members.

Usage:
    python scripts/generate_seed_sql.py

Requirements:
    pip install passlib bcrypt

Output:
    1. Prints INSERT SQL to stdout — paste this into Supabase SQL Editor
    2. Saves credentials to scripts/SEEDED_CREDENTIALS.txt (gitignored)

The passwords are randomly generated and bcrypt-hashed before insertion.
"""
import json
import secrets
from pathlib import Path

from passlib.hash import bcrypt

SEED_DATA = Path(__file__).resolve().parent / "seed_data.json"
CREDENTIALS_FILE = Path(__file__).resolve().parent / "SEEDED_CREDENTIALS.txt"


def main():
    with open(SEED_DATA) as f:
        members = json.load(f)

    credentials = []
    insert_values = []

    for m in members:
        password = secrets.token_urlsafe(12)
        hashed = bcrypt.hash(password)

        name = m["name"].replace("'", "''")
        username = m["username"]
        email = m.get("email", "")

        insert_values.append(
            f"    ('{name}', '', '{username}', '{hashed}', '{email}')"
        )
        credentials.append(f"{username:25s} {email:30s} {password}")

    cols = ("name", "nickname", "username", "hashed_password", "email")

    print("-- Generated by generate_seed_sql.py")
    print("-- Paste this into Supabase SQL Editor and run it.\n")
    print(f"INSERT INTO member ({', '.join(cols)}) VALUES")
    print(",\n".join(insert_values) + ";")

    header = (
        "\n\nSEEDED CREDENTIALS - SAVE THESE, THEY WON'T BE SHOWN AGAIN\n"
        + "=" * 85 + "\n"
        + f"{'username':25s} {'email':30s} password\n"
        + "-" * 85
    )
    footer = "=" * 85 + "\n"

    output = header + "\n" + "\n".join(credentials) + "\n" + footer
    print(output, file=open(CREDENTIALS_FILE, "w", encoding="utf-8"))
    print(f"\nCredentials also saved to: {CREDENTIALS_FILE}\n")


if __name__ == "__main__":
    main()
