-- Generated by generate_seed_sql.py
-- Paste this into Supabase SQL Editor and run it.

INSERT INTO member (name, nickname, username, hashed_password, email) VALUES
    ('Md Sojib', '', 'sojib@elonboys', '$2b$12$dR8v8f1J6qgsB40qDTJnxePeuJI1Rr4R9BGLRpJKmF5P033LyjXhe', '20101030@uap-bd.edu'),
    ('Md. Nazmul Islam Nayem', '', 'nayem@elonboys', '$2b$12$g2GeRP4fkXFV0iLyCLykQ.hJFPGs1XN.QfZ1XdcW1OHHJB/ONqDAi', '20101013@uap-bd.edu'),
    ('Md. Mehedi Hasan', '', 'mehedi@elonboys', '$2b$12$1TwMpVatWDiXjBjfCIrt0uKcmtpRI7ZgSoNnWPNe6ZRONRIml/.ce', '20101007@uap-bd.edu'),
    ('Apurba Datta', '', 'apurba@elonboys', '$2b$12$WdjiH9xrDrIPBhfi/R8tHOlIuLa3IQVcujC.9Kla7rxM6YlBueQDK', '20101040@uap-bd.edu'),
    ('Farhan Jarif Nibir', '', 'nibir@elonboys', '$2b$12$2Ht6H3B6leHyCSltWGMReuf.dVMur7qCj.n5I76P52vfOql4zz7fq', '20101053@uap-bd.edu'),
    ('Safi Ullah Chowdhury', '', 'safi@elonboys', '$2b$12$K.N6mjhhDpyh9bqLPYsOwOQgvdgQTC5CGqbsUpPlb/0hZkz7VBvvy', '20101010@uap-bd.edu'),
    ('Niaz Mahmud', '', 'niaz@elonboys', '$2b$12$yD2XfcHJy.usztPihGAF/uU7uZNjAR4pJBBdFVelRAuvV1DdLpNbS', '20101019@uap-bd.edu'),
    ('Al Zubayer Saad', '', 'saad@elonboys', '$2b$12$1lpyYJU1Z/XxXcK5dCQ23OGgyI390CW/tCraph4OP7IQSTCYgqBJO', '20101027@uap-bd.edu'),
    ('MAHIR TAJWAR BHUIYAN', '', 'mahir@elonboys', '$2b$12$/dzAhdKbI3S9kV52QOrCuOxm.GKblFedXaBMnRoMxnif8k0q5PLJa', '20101034@uap-bd.edu'),
    ('Md. Rufiad Rahi Arnob', '', 'arnob@elonboys', '$2b$12$7Lw7vxDbU5ruNsqblWSEp.YMts.z4RivGBKGGc.OkSetEThUqgYRG', '20101006@uap-bd.edu'),
    ('Mahfuj Mahtab Mohot', '', 'mohot@elonboys', '$2b$12$DY7fCadp9SeWXZzpxOLJfeKmApoiKks1OcVCShkv384oFhcN5/v12', '19201003@uap-bd.edu');

Credentials also saved to: X:\elon_boys\scripts\SEEDED_CREDENTIALS.txt

